import {
  GraduationCap,
  University,
  Library,
  BookOpen,
  User,
  Users,
  Search,
  Settings,

  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  Menu,
  MoreHorizontal,
  MapPinned,

  Plus,
  Minus,
  Check,
  X,
  Pencil,
  Trash2,
  Copy,
  Upload,
  Download,
  ExternalLink,

  File,
  Files,
  FileText,
  FileCheck,
  FileWarning,
  Folder,
  FolderOpen,
  ClipboardList,
  Table,

  Bookmark,
  NotebookPen,
  Presentation,
  Calendar,
  CalendarPlus,
  CalendarCheck,
  Clock3,
  GraduationCap as GraduationCapAlt,
  Microscope,

  Building2,
  Navigation,
  Map,
  CarFront,
  Bus,
  Hotel,
  UtensilsCrossed,
  Mail,
  Phone,

  CircleCheck,
  CircleX,
  TriangleAlert,
  AlertCircle,
  Info,
  CircleHelp,
  ShieldCheck,
  ShieldAlert,
  Lock,
} from 'lucide-react'

export const ICON_CATEGORIES = {
  core: {
    title: 'Базовые',
    description: 'Базовые иконки для ключевых сущностей и общих UI-сценариев.',
    icons: [
      'academic',
      'university',
      'library',
      'bookOpen',
      'user',
      'users',
      'search',
      'settings',
    ],
  },
  navigation: {
    title: 'Навигация',
    description: 'Навигация, переходы, раскрытие, overflow-меню и географическая привязка.',
    icons: [
      'chevronDown',
      'chevronLeft',
      'chevronRight',
      'arrowLeft',
      'arrowRight',
      'menu',
      'moreHorizontal',
      'mapPinned',
    ],
  },
  actions: {
    title: 'Действия',
    description: 'Базовые действия интерфейса: добавить, удалить, редактировать, открыть, загрузить.',
    icons: [
      'plus',
      'minus',
      'check',
      'close',
      'pencil',
      'trash2',
      'copy',
      'upload',
      'download',
      'externalLink',
    ],
  },
  filesData: {
    title: 'Файлы и данные',
    description: 'Документы, таблицы, файловые группы, списки и сценарии, связанные с данными.',
    icons: [
      'file',
      'files',
      'fileText',
      'fileCheck',
      'fileWarning',
      'folder',
      'folderOpen',
      'clipboardList',
      'table',
    ],
  },
  academics: {
    title: 'Учебный процесс',
    description: 'Обучение, расписание, курсы, события и академическая деятельность.',
    icons: [
      'bookmark',
      'notebookPen',
      'presentation',
      'calendar',
      'calendarPlus',
      'calendarCheck',
      'clock3',
      'graduationCapAlt',
      'microscope',
    ],
  },
  campus: {
    title: 'Корпуса и сервисы',
    description: 'Корпуса, транспорт, сервисы, контакты и инфраструктура.',
    icons: [
      'building2',
      'navigation',
      'map',
      'carFront',
      'bus',
      'hotel',
      'utensilsCrossed',
      'mail',
      'phone',
    ],
  },
  status: {
    title: 'Статусы и обратная связь',
    description: 'Статусы, подтверждения, предупреждения, помощь и безопасность.',
    icons: [
      'circleCheck',
      'circleX',
      'triangleAlert',
      'alertCircle',
      'info',
      'circleHelp',
      'shieldCheck',
      'shieldAlert',
      'lock',
    ],
  },
}

export const ICON_REGISTRY = {
  academic: {
    component: GraduationCap,
    category: 'core',
    title: 'Академическая деятельность',
    note: 'Образование, степень, обучение, академическая идентичность.',
  },
  university: {
    component: University,
    category: 'core',
    title: 'Университет',
    note: 'Учебное заведение, факультет, идентичность корпуса.',
  },
  library: {
    component: Library,
    category: 'core',
    title: 'Библиотека',
    note: 'Библиотечные сервисы и фонды.',
  },
  bookOpen: {
    component: BookOpen,
    category: 'core',
    title: 'Открытая книга',
    note: 'Курсы, материалы, учебный контент.',
  },
  user: {
    component: User,
    category: 'core',
    title: 'Пользователь',
    note: 'Профиль, человек, учётная запись.',
  },
  users: {
    component: Users,
    category: 'core',
    title: 'Группа пользователей',
    note: 'Студенты, сотрудники, комиссии, группы.',
  },
  search: {
    component: Search,
    category: 'core',
    title: 'Поиск',
    note: 'Поиск по сервисам и контенту.',
  },
  settings: {
    component: Settings,
    category: 'core',
    title: 'Настройки',
    note: 'Параметры и элементы управления интерфейсом.',
  },

  chevronDown: {
    component: ChevronDown,
    category: 'navigation',
    title: 'Шеврон вниз',
    note: 'Выпадающий список и управление раскрытием.',
  },
  chevronLeft: {
    component: ChevronLeft,
    category: 'navigation',
    title: 'Шеврон влево',
    note: 'Предыдущее состояние или свёрнутый вид.',
  },
  chevronRight: {
    component: ChevronRight,
    category: 'navigation',
    title: 'Шеврон вправо',
    note: 'Следующее состояние или раскрытый вид.',
  },
  arrowLeft: {
    component: ArrowLeft,
    category: 'navigation',
    title: 'Стрелка влево',
    note: 'Навигация назад.',
  },
  arrowRight: {
    component: ArrowRight,
    category: 'navigation',
    title: 'Стрелка вправо',
    note: 'Навигация вперёд.',
  },
  menu: {
    component: Menu,
    category: 'navigation',
    title: 'Меню',
    note: 'Мобильная и свёрнутая навигация.',
  },
  moreHorizontal: {
    component: MoreHorizontal,
    category: 'navigation',
    title: 'Ещё',
    note: 'Меню дополнительных действий.',
  },
  mapPinned: {
    component: MapPinned,
    category: 'navigation',
    title: 'Точка на карте',
    note: 'Закреплённая локация корпуса или адрес.',
  },

  plus: {
    component: Plus,
    category: 'actions',
    title: 'Плюс',
    note: 'Добавить или создать новый элемент.',
  },
  minus: {
    component: Minus,
    category: 'actions',
    title: 'Минус',
    note: 'Удалить, свернуть или уменьшить.',
  },
  check: {
    component: Check,
    category: 'actions',
    title: 'Галочка',
    note: 'Подтверждение выбора, отметка, выполнено.',
  },
  close: {
    component: X,
    category: 'actions',
    title: 'Закрыть',
    note: 'Закрытие, сброс или отмена действия.',
  },
  pencil: {
    component: Pencil,
    category: 'actions',
    title: 'Редактирование',
    note: 'Действие редактирования.',
  },
  trash2: {
    component: Trash2,
    category: 'actions',
    title: 'Удаление',
    note: 'Действие удаления.',
  },
  copy: {
    component: Copy,
    category: 'actions',
    title: 'Копирование',
    note: 'Дублировать или скопировать содержимое.',
  },
  upload: {
    component: Upload,
    category: 'actions',
    title: 'Загрузка',
    note: 'Загрузить документ или вложение.',
  },
  download: {
    component: Download,
    category: 'actions',
    title: 'Скачивание',
    note: 'Скачать файл или справку.',
  },
  externalLink: {
    component: ExternalLink,
    category: 'actions',
    title: 'Внешняя ссылка',
    note: 'Открыть внешний ресурс.',
  },

  file: {
    component: File,
    category: 'filesData',
    title: 'Файл',
    note: 'Универсальный файловый объект.',
  },
  files: {
    component: Files,
    category: 'filesData',
    title: 'Файлы',
    note: 'Несколько документов или вложений.',
  },
  fileText: {
    component: FileText,
    category: 'filesData',
    title: 'Текстовый файл',
    note: 'Заявление, справка, текстовый документ.',
  },
  fileCheck: {
    component: FileCheck,
    category: 'filesData',
    title: 'Проверенный файл',
    note: 'Проверенный или утверждённый файл.',
  },
  fileWarning: {
    component: FileWarning,
    category: 'filesData',
    title: 'Файл с предупреждением',
    note: 'Проблемный или неполный файл.',
  },
  folder: {
    component: Folder,
    category: 'filesData',
    title: 'Папка',
    note: 'Коллекция документов или категория.',
  },
  folderOpen: {
    component: FolderOpen,
    category: 'filesData',
    title: 'Открытая папка',
    note: 'Открытая или активная коллекция.',
  },
  clipboardList: {
    component: ClipboardList,
    category: 'filesData',
    title: 'Список на планшете',
    note: 'Чек-лист, очередь, список записей.',
  },
  table: {
    component: Table,
    category: 'filesData',
    title: 'Таблица',
    note: 'Табличные данные и сетки.',
  },

  bookmark: {
    component: Bookmark,
    category: 'academics',
    title: 'Закладка',
    note: 'Сохранённый курс или важный материал.',
  },
  notebookPen: {
    component: NotebookPen,
    category: 'academics',
    title: 'Блокнот',
    note: 'Учебные записи, задания, письмо.',
  },
  presentation: {
    component: Presentation,
    category: 'academics',
    title: 'Презентация',
    note: 'Лекция, семинар, учебная презентация.',
  },
  calendar: {
    component: Calendar,
    category: 'academics',
    title: 'Календарь',
    note: 'Учебный календарь и даты.',
  },
  calendarPlus: {
    component: CalendarPlus,
    category: 'academics',
    title: 'Календарь с добавлением',
    note: 'Добавить событие или дату.',
  },
  calendarCheck: {
    component: CalendarCheck,
    category: 'academics',
    title: 'Подтверждённый календарь',
    note: 'Подтверждённое учебное событие или дата.',
  },
  clock3: {
    component: Clock3,
    category: 'academics',
    title: 'Часы',
    note: 'Расписание, время, сроки.',
  },
  graduationCapAlt: {
    component: GraduationCapAlt,
    category: 'academics',
    title: 'Академическая шапочка',
    note: 'Академические достижения.',
  },
  microscope: {
    component: Microscope,
    category: 'academics',
    title: 'Микроскоп',
    note: 'Исследовательская и лабораторная деятельность.',
  },

  building2: {
    component: Building2,
    category: 'campus',
    title: 'Здание',
    note: 'Подразделения, кабинеты, корпуса.',
  },
  navigation: {
    component: Navigation,
    category: 'campus',
    title: 'Маршрут',
    note: 'Построение маршрута и ориентирование.',
  },
  map: {
    component: Map,
    category: 'campus',
    title: 'Карта',
    note: 'Карта корпуса и навигация.',
  },
  carFront: {
    component: CarFront,
    category: 'campus',
    title: 'Автомобиль',
    note: 'Парковка и возможность проезда на автомобиле.',
  },
  bus: {
    component: Bus,
    category: 'campus',
    title: 'Автобус',
    note: 'Доступ на общественном транспорте.',
  },
  hotel: {
    component: Hotel,
    category: 'campus',
    title: 'Проживание',
    note: 'Общежитие или размещение.',
  },
  utensilsCrossed: {
    component: UtensilsCrossed,
    category: 'campus',
    title: 'Питание',
    note: 'Столовая и сервисы питания.',
  },
  mail: {
    component: Mail,
    category: 'campus',
    title: 'Почта',
    note: 'Электронная почта и официальная коммуникация.',
  },
  phone: {
    component: Phone,
    category: 'campus',
    title: 'Телефон',
    note: 'Звонок и линия поддержки.',
  },

  circleCheck: {
    component: CircleCheck,
    category: 'status',
    title: 'Подтверждение',
    note: 'Успех, подтверждение, завершение.',
  },
  circleX: {
    component: CircleX,
    category: 'status',
    title: 'Ошибка',
    note: 'Ошибка, отклонение, некорректное состояние.',
  },
  triangleAlert: {
    component: TriangleAlert,
    category: 'status',
    title: 'Предупреждение',
    note: 'Призыв к осторожности.',
  },
  alertCircle: {
    component: AlertCircle,
    category: 'status',
    title: 'Важное уведомление',
    note: 'Важная проблема.',
  },
  info: {
    component: Info,
    category: 'status',
    title: 'Информация',
    note: 'Информация и дополнительное пояснение.',
  },
  circleHelp: {
    component: CircleHelp,
    category: 'status',
    title: 'Помощь',
    note: 'Помощь, подсказка, сопровождение.',
  },
  shieldCheck: {
    component: ShieldCheck,
    category: 'status',
    title: 'Безопасность подтверждена',
    note: 'Проверенная безопасность и безопасный доступ.',
  },
  shieldAlert: {
    component: ShieldAlert,
    category: 'status',
    title: 'Предупреждение безопасности',
    note: 'Предупреждение безопасности или ограниченный доступ.',
  },
  lock: {
    component: Lock,
    category: 'status',
    title: 'Защита',
    note: 'Защищённый контент или безопасное действие.',
  },
}

export const ICON_NAMES = Object.keys(ICON_REGISTRY)

export const getIconComponent = (name) => ICON_REGISTRY[name]?.component || null