import {
  GraduationCap,
  University,
  Library,
  BookOpen,
  User,
  Users,
  Search,
  Settings,

  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  Menu,
  MoreHorizontal,
  MapPinned,

  Plus,
  Minus,
  Pencil,
  Trash2,
  Copy,
  Upload,
  Download,
  ExternalLink,

  File,
  Files,
  FileText,
  FileCheck,
  FileWarning,
  Folder,
  FolderOpen,
  ClipboardList,
  Table,

  Bookmark,
  NotebookPen,
  Presentation,
  Calendar,
  CalendarPlus,
  CalendarCheck,
  Clock3,
  GraduationCap as GraduationCapAlt,
  Microscope,

  Building2,
  Navigation,
  Map,
  CarFront,
  Bus,
  Hotel,
  UtensilsCrossed,
  Mail,
  Phone,

  CircleCheck,
  CircleX,
  TriangleAlert,
  AlertCircle,
  Info,
  CircleHelp,
  ShieldCheck,
  ShieldAlert,
  Lock,
} from 'lucide-react'

export const ICON_CATEGORIES = {
  core: {
    title: 'Core',
    description: 'Базовые иконки для ключевых сущностей и общих UI-сценариев.',
    icons: [
      'academic',
      'university',
      'library',
      'bookOpen',
      'user',
      'users',
      'search',
      'settings',
    ],
  },
  navigation: {
    title: 'Navigation',
    description: 'Навигация, переходы, раскрытие, overflow-меню и географическая привязка.',
    icons: [
      'chevronDown',
      'chevronLeft',
      'chevronRight',
      'arrowLeft',
      'arrowRight',
      'menu',
      'moreHorizontal',
      'mapPinned',
    ],
  },
  actions: {
    title: 'Actions',
    description: 'Базовые действия интерфейса: добавить, удалить, редактировать, открыть, загрузить.',
    icons: [
      'plus',
      'minus',
      'pencil',
      'trash2',
      'copy',
      'upload',
      'download',
      'externalLink',
    ],
  },
  filesData: {
    title: 'Files & Data',
    description: 'Документы, таблицы, файловые группы, списки и data-related сценарии.',
    icons: [
      'file',
      'files',
      'fileText',
      'fileCheck',
      'fileWarning',
      'folder',
      'folderOpen',
      'clipboardList',
      'table',
    ],
  },
  academics: {
    title: 'Academics',
    description: 'Обучение, расписание, курсы, события и академическая деятельность.',
    icons: [
      'bookmark',
      'notebookPen',
      'presentation',
      'calendar',
      'calendarPlus',
      'calendarCheck',
      'clock3',
      'graduationCapAlt',
      'microscope',
    ],
  },
  campus: {
    title: 'Campus & Services',
    description: 'Кампус, корпуса, транспорт, сервисы, контакты и инфраструктура.',
    icons: [
      'building2',
      'navigation',
      'map',
      'carFront',
      'bus',
      'hotel',
      'utensilsCrossed',
      'mail',
      'phone',
    ],
  },
  status: {
    title: 'Status & Feedback',
    description: 'Статусы, подтверждения, предупреждения, помощь и безопасность.',
    icons: [
      'circleCheck',
      'circleX',
      'triangleAlert',
      'alertCircle',
      'info',
      'circleHelp',
      'shieldCheck',
      'shieldAlert',
      'lock',
    ],
  },
}

export const ICON_REGISTRY = {
  academic: {
    component: GraduationCap,
    category: 'core',
    title: 'Academic',
    note: 'Education, degree, study, academic identity.',
  },
  university: {
    component: University,
    category: 'core',
    title: 'University',
    note: 'Institution, faculty, campus identity.',
  },
  library: {
    component: Library,
    category: 'core',
    title: 'Library',
    note: 'Library services and collections.',
  },
  bookOpen: {
    component: BookOpen,
    category: 'core',
    title: 'Book open',
    note: 'Courses, materials, learning content.',
  },
  user: {
    component: User,
    category: 'core',
    title: 'User',
    note: 'Profile, person, account.',
  },
  users: {
    component: Users,
    category: 'core',
    title: 'Users',
    note: 'Students, staff, committees, groups.',
  },
  search: {
    component: Search,
    category: 'core',
    title: 'Search',
    note: 'Search across services and content.',
  },
  settings: {
    component: Settings,
    category: 'core',
    title: 'Settings',
    note: 'Preferences and interface controls.',
  },

  chevronDown: {
    component: ChevronDown,
    category: 'navigation',
    title: 'Chevron down',
    note: 'Dropdown and disclosure control.',
  },
  chevronLeft: {
    component: ChevronLeft,
    category: 'navigation',
    title: 'Chevron left',
    note: 'Previous or collapsed state.',
  },
  chevronRight: {
    component: ChevronRight,
    category: 'navigation',
    title: 'Chevron right',
    note: 'Next or expanded state.',
  },
  arrowLeft: {
    component: ArrowLeft,
    category: 'navigation',
    title: 'Arrow left',
    note: 'Back navigation.',
  },
  arrowRight: {
    component: ArrowRight,
    category: 'navigation',
    title: 'Arrow right',
    note: 'Forward navigation.',
  },
  menu: {
    component: Menu,
    category: 'navigation',
    title: 'Menu',
    note: 'Mobile and collapsed navigation.',
  },
  moreHorizontal: {
    component: MoreHorizontal,
    category: 'navigation',
    title: 'More horizontal',
    note: 'Overflow actions menu.',
  },
  mapPinned: {
    component: MapPinned,
    category: 'navigation',
    title: 'Map pinned',
    note: 'Pinned campus location or address.',
  },

  plus: {
    component: Plus,
    category: 'actions',
    title: 'Plus',
    note: 'Add or create new item.',
  },
  minus: {
    component: Minus,
    category: 'actions',
    title: 'Minus',
    note: 'Remove, collapse or decrease.',
  },
  pencil: {
    component: Pencil,
    category: 'actions',
    title: 'Pencil',
    note: 'Edit action.',
  },
  trash2: {
    component: Trash2,
    category: 'actions',
    title: 'Trash',
    note: 'Delete action.',
  },
  copy: {
    component: Copy,
    category: 'actions',
    title: 'Copy',
    note: 'Duplicate or copy content.',
  },
  upload: {
    component: Upload,
    category: 'actions',
    title: 'Upload',
    note: 'Upload document or attachment.',
  },
  download: {
    component: Download,
    category: 'actions',
    title: 'Download',
    note: 'Download file or certificate.',
  },
  externalLink: {
    component: ExternalLink,
    category: 'actions',
    title: 'External link',
    note: 'Open external resource.',
  },

  file: {
    component: File,
    category: 'filesData',
    title: 'File',
    note: 'Generic file object.',
  },
  files: {
    component: Files,
    category: 'filesData',
    title: 'Files',
    note: 'Multiple documents or attachments.',
  },
  fileText: {
    component: FileText,
    category: 'filesData',
    title: 'File text',
    note: 'Application, statement, text document.',
  },
  fileCheck: {
    component: FileCheck,
    category: 'filesData',
    title: 'File check',
    note: 'Verified or approved file.',
  },
  fileWarning: {
    component: FileWarning,
    category: 'filesData',
    title: 'File warning',
    note: 'Problematic or incomplete file.',
  },
  folder: {
    component: Folder,
    category: 'filesData',
    title: 'Folder',
    note: 'Document collection or category.',
  },
  folderOpen: {
    component: FolderOpen,
    category: 'filesData',
    title: 'Folder open',
    note: 'Opened or active collection.',
  },
  clipboardList: {
    component: ClipboardList,
    category: 'filesData',
    title: 'Clipboard list',
    note: 'Checklist, queue, records list.',
  },
  table: {
    component: Table,
    category: 'filesData',
    title: 'Table',
    note: 'Tabular data and grids.',
  },

  bookmark: {
    component: Bookmark,
    category: 'academics',
    title: 'Bookmark',
    note: 'Saved course or important material.',
  },
  notebookPen: {
    component: NotebookPen,
    category: 'academics',
    title: 'Notebook pen',
    note: 'Study notes, coursework, writing.',
  },
  presentation: {
    component: Presentation,
    category: 'academics',
    title: 'Presentation',
    note: 'Lecture, seminar, educational presentation.',
  },
  calendar: {
    component: Calendar,
    category: 'academics',
    title: 'Calendar',
    note: 'Academic calendar and dates.',
  },
  calendarPlus: {
    component: CalendarPlus,
    category: 'academics',
    title: 'Calendar plus',
    note: 'Add event or date entry.',
  },
  calendarCheck: {
    component: CalendarCheck,
    category: 'academics',
    title: 'Calendar check',
    note: 'Confirmed academic event or date.',
  },
  clock3: {
    component: Clock3,
    category: 'academics',
    title: 'Clock',
    note: 'Schedule, time, deadlines.',
  },
  graduationCapAlt: {
    component: GraduationCapAlt,
    category: 'academics',
    title: 'Graduation cap',
    note: 'Academic achievement and degree context.',
  },
  microscope: {
    component: Microscope,
    category: 'academics',
    title: 'Microscope',
    note: 'Research and laboratory activities.',
  },

  building2: {
    component: Building2,
    category: 'campus',
    title: 'Building',
    note: 'Departments, offices, buildings.',
  },
  navigation: {
    component: Navigation,
    category: 'campus',
    title: 'Navigation',
    note: 'Route guidance and orientation.',
  },
  map: {
    component: Map,
    category: 'campus',
    title: 'Map',
    note: 'Campus map and wayfinding.',
  },
  carFront: {
    component: CarFront,
    category: 'campus',
    title: 'Car front',
    note: 'Parking and automobile access.',
  },
  bus: {
    component: Bus,
    category: 'campus',
    title: 'Bus',
    note: 'Public transport access.',
  },
  hotel: {
    component: Hotel,
    category: 'campus',
    title: 'Hotel',
    note: 'Dormitory or accommodation context.',
  },
  utensilsCrossed: {
    component: UtensilsCrossed,
    category: 'campus',
    title: 'Utensils crossed',
    note: 'Cafeteria and dining services.',
  },
  mail: {
    component: Mail,
    category: 'campus',
    title: 'Mail',
    note: 'Email and official communication.',
  },
  phone: {
    component: Phone,
    category: 'campus',
    title: 'Phone',
    note: 'Call and support line.',
  },

  circleCheck: {
    component: CircleCheck,
    category: 'status',
    title: 'Circle check',
    note: 'Success, confirmation, completion.',
  },
  circleX: {
    component: CircleX,
    category: 'status',
    title: 'Circle X',
    note: 'Error, rejection, invalid state.',
  },
  triangleAlert: {
    component: TriangleAlert,
    category: 'status',
    title: 'Triangle alert',
    note: 'Warning and caution.',
  },
  alertCircle: {
    component: AlertCircle,
    category: 'status',
    title: 'Alert circle',
    note: 'Important issue or alert state.',
  },
  info: {
    component: Info,
    category: 'status',
    title: 'Info',
    note: 'Information and secondary explanation.',
  },
  circleHelp: {
    component: CircleHelp,
    category: 'status',
    title: 'Help',
    note: 'Help, hint, support guidance.',
  },
  shieldCheck: {
    component: ShieldCheck,
    category: 'status',
    title: 'Shield check',
    note: 'Verified security and safe access.',
  },
  shieldAlert: {
    component: ShieldAlert,
    category: 'status',
    title: 'Shield alert',
    note: 'Security warning or restricted access.',
  },
  lock: {
    component: Lock,
    category: 'status',
    title: 'Lock',
    note: 'Protected content or secured action.',
  },
}

export const ICON_NAMES = Object.keys(ICON_REGISTRY)

export const getIconComponent = (name) => ICON_REGISTRY[name]?.component || null